<?php
// This script and data application were generated by AppGini 5.92
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/product.php");
	include_once("{$currDir}/product_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('product');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = 'product';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`product`.`id`" => "id",
		"`product`.`name`" => "name",
		"`product`.`uploads`" => "uploads",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`product`.`id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`product`.`id`" => "id",
		"`product`.`name`" => "name",
		"`product`.`uploads`" => "uploads",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`product`.`id`" => "ID",
		"`product`.`name`" => "Name",
		"`product`.`uploads`" => "Uploads",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`product`.`id`" => "id",
		"`product`.`name`" => "name",
		"`product`.`uploads`" => "uploads",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`product` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'product_view.php';
	$x->RedirectAfterInsert = 'product_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Product';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`product`.`id`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Name', ];
	$x->ColFieldName = ['name', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/product_templateTV.html';
	$x->SelectedTemplate = 'templates/product_templateTVS.html';
	$x->TemplateDV = 'templates/product_templateDV.html';
	$x->TemplateDVP = 'templates/product_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `product`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='product' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `product`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='product' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`product`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: product_init
	$render = true;
	if(function_exists('product_init')) {
		$args = [];
		$render = product_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: product_header
	$headerCode = '';
	if(function_exists('product_header')) {
		$args = [];
		$headerCode = product_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: product_footer
	$footerCode = '';
	if(function_exists('product_footer')) {
		$args = [];
		$footerCode = product_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
