<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/tmp_tables_fields.php");
	include_once("{$currDir}/tmp_tables_fields_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('tmp_tables_fields');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tmp_tables_fields';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tmp_tables_fields`.`table_filed`" => "table_filed",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tmp_tables_fields`.`table_filed`" => "table_filed",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tmp_tables_fields`.`table_filed`" => "Table filed",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tmp_tables_fields`.`table_filed`" => "table_filed",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`tmp_tables_fields` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tmp_tables_fields_view.php';
	$x->RedirectAfterInsert = 'tmp_tables_fields_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Tmp';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`tmp_tables_fields`.`table_filed`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Table filed', ];
	$x->ColFieldName = ['table_filed', ];
	$x->ColNumber  = [1, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tmp_tables_fields_templateTV.html';
	$x->SelectedTemplate = 'templates/tmp_tables_fields_templateTVS.html';
	$x->TemplateDV = 'templates/tmp_tables_fields_templateDV.html';
	$x->TemplateDVP = 'templates/tmp_tables_fields_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `tmp_tables_fields`.`table_filed`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='tmp_tables_fields' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `tmp_tables_fields`.`table_filed`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='tmp_tables_fields' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`tmp_tables_fields`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tmp_tables_fields_init
	$render = true;
	if(function_exists('tmp_tables_fields_init')) {
		$args = [];
		$render = tmp_tables_fields_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tmp_tables_fields_header
	$headerCode = '';
	if(function_exists('tmp_tables_fields_header')) {
		$args = [];
		$headerCode = tmp_tables_fields_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tmp_tables_fields_footer
	$footerCode = '';
	if(function_exists('tmp_tables_fields_footer')) {
		$args = [];
		$footerCode = tmp_tables_fields_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
