<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/todos.php");
	include_once("{$currDir}/todos_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('todos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'todos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`todos`.`id`" => "id",
		"`todos`.`tarea`" => "tarea",
		"if(`todos`.`dateInit`,date_format(`todos`.`dateInit`,'%d/%m/%Y'),'')" => "dateInit",
		"if(`todos`.`dateEnd`,date_format(`todos`.`dateEnd`,'%d/%m/%Y'),'')" => "dateEnd",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`todos`.`id`',
		2 => 2,
		3 => '`todos`.`dateInit`',
		4 => '`todos`.`dateEnd`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`todos`.`id`" => "id",
		"`todos`.`tarea`" => "tarea",
		"if(`todos`.`dateInit`,date_format(`todos`.`dateInit`,'%d/%m/%Y'),'')" => "dateInit",
		"if(`todos`.`dateEnd`,date_format(`todos`.`dateEnd`,'%d/%m/%Y'),'')" => "dateEnd",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`todos`.`id`" => "ID",
		"`todos`.`tarea`" => "Tareas",
		"`todos`.`dateInit`" => "Date Init",
		"`todos`.`dateEnd`" => "Date End",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`todos`.`id`" => "id",
		"`todos`.`tarea`" => "tarea",
		"if(`todos`.`dateInit`,date_format(`todos`.`dateInit`,'%d/%m/%Y'),'')" => "dateInit",
		"if(`todos`.`dateEnd`,date_format(`todos`.`dateEnd`,'%d/%m/%Y'),'')" => "dateEnd",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`todos` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'todos_view.php';
	$x->RedirectAfterInsert = 'todos_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Todos';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`todos`.`id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Tareas', 'Date Init', 'Date End', ];
	$x->ColFieldName = ['tarea', 'dateInit', 'dateEnd', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/todos_templateTV.html';
	$x->SelectedTemplate = 'templates/todos_templateTVS.html';
	$x->TemplateDV = 'templates/todos_templateDV.html';
	$x->TemplateDVP = 'templates/todos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `todos`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='todos' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `todos`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='todos' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`todos`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: todos_init
	$render = true;
	if(function_exists('todos_init')) {
		$args = [];
		$render = todos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: todos_header
	$headerCode = '';
	if(function_exists('todos_header')) {
		$args = [];
		$headerCode = todos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: todos_footer
	$footerCode = '';
	if(function_exists('todos_footer')) {
		$args = [];
		$footerCode = todos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
