<?php
// This script and data application were generated by AppGini 5.94
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/view_mebership_groups.php");
	include_once("{$currDir}/view_mebership_groups_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('view_mebership_groups');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout(function() { window.location = "index.php?signOut=1"; }, 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = 'view_mebership_groups';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`view_mebership_groups`.`groupID`" => "groupID",
		"`view_mebership_groups`.`name`" => "name",
		"`view_mebership_groups`.`description`" => "description",
		"`view_mebership_groups`.`allowSignup`" => "allowSignup",
		"`view_mebership_groups`.`needsApproval`" => "needsApproval",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`view_mebership_groups`.`groupID`" => "groupID",
		"`view_mebership_groups`.`name`" => "name",
		"`view_mebership_groups`.`description`" => "description",
		"`view_mebership_groups`.`allowSignup`" => "allowSignup",
		"`view_mebership_groups`.`needsApproval`" => "needsApproval",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`view_mebership_groups`.`groupID`" => "GroupID",
		"`view_mebership_groups`.`name`" => "Name",
		"`view_mebership_groups`.`description`" => "Description",
		"`view_mebership_groups`.`allowSignup`" => "AllowSingUp",
		"`view_mebership_groups`.`needsApproval`" => "NeedsApprlbals",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`view_mebership_groups`.`groupID`" => "groupID",
		"`view_mebership_groups`.`name`" => "name",
		"`view_mebership_groups`.`description`" => "description",
		"`view_mebership_groups`.`allowSignup`" => "allowSignup",
		"`view_mebership_groups`.`needsApproval`" => "needsApproval",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`view_mebership_groups` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'view_mebership_groups_view.php';
	$x->RedirectAfterInsert = 'view_mebership_groups_view.php?SelectedID=#ID#';
	$x->TableTitle = 'View mebership group';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`view_mebership_groups`.`groupID`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['GroupID', 'Name', 'Description', 'AllowSingUp', 'NeedsApprlbals', ];
	$x->ColFieldName = ['groupID', 'name', 'description', 'allowSignup', 'needsApproval', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/view_mebership_groups_templateTV.html';
	$x->SelectedTemplate = 'templates/view_mebership_groups_templateTVS.html';
	$x->TemplateDV = 'templates/view_mebership_groups_templateDV.html';
	$x->TemplateDVP = 'templates/view_mebership_groups_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `view_mebership_groups`.`groupID`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='view_mebership_groups' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `view_mebership_groups`.`groupID`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='view_mebership_groups' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`view_mebership_groups`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: view_mebership_groups_init
	$render = true;
	if(function_exists('view_mebership_groups_init')) {
		$args = [];
		$render = view_mebership_groups_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: view_mebership_groups_header
	$headerCode = '';
	if(function_exists('view_mebership_groups_header')) {
		$args = [];
		$headerCode = view_mebership_groups_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: view_mebership_groups_footer
	$footerCode = '';
	if(function_exists('view_mebership_groups_footer')) {
		$args = [];
		$footerCode = view_mebership_groups_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
